<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster.Master" AutoEventWireup="true" CodeBehind="UpdateDeletePatients.aspx.cs" Inherits="HospitalManagementSystem.Paitients.UpdateDeletePatients" %>

<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="ajaxToolkit" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../css/Design1.css" rel="stylesheet" type="text/css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div id="content">
        <div class="post">
            <ul>
                <li id="search" style="visibility: visible;">
                    <h2>Search</h2>
                    <form method="get" action="index.aspx">
                        <fieldset>
                            <asp:TextBox ID="txtIDNo" CssClass="s" runat="server"></asp:TextBox>
                            <ajaxToolkit:MaskedEditExtender ID="txtIDNo_MaskedEditExtender" runat="server" Mask="(999999)-9999-99-9" MaskType="Number" TargetControlID="txtIDNo" />
                            <asp:Button ID="btnSubmit" CssClass="x" runat="server" Text="submit" OnClick="btnSubmit_Click" />

                        </fieldset>
                    </form>
                </li>
            </ul>
            <div class="entry">
                <form id="form1">
                <div id="scroller" style="overflow:auto;">
                    <asp:GridView ID="datagrid" runat="server" CssClass="mydatagrid" PagerStyle-CssClass="pager"
                        HeaderStyle-CssClass="header" RowStyle-CssClass="rows"
                        AllowPaging="True" AutoGenerateDeleteButton="True" CellPadding="1" PagerSettings-PageButtonCount="5" OnPageIndexChanging="datagrid_PageIndexChanging" OnRowDeleting="datagrid_RowDeleting" AutoGenerateSelectButton="True" OnSelectedIndexChanged="datagrid_SelectedIndexChanged" >
                    </asp:GridView>
                </div>
                </form>
            </div>
        </div>
    </div>
</asp:Content>
