<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster.Master" AutoEventWireup="true" CodeBehind="Facility.aspx.cs" Inherits="HospitalManagementSystem.AdminPages.Facility" %>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="ajaxToolkit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../css/Design1.css" rel="stylesheet" type="text/css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <div id="content">
        <div class="post">
            <div class="entry">
                <form id="form1">
                <div id="scroller" style="overflow:auto;">
                    <asp:GridView ID="datagrid" runat="server" CssClass="mydatagrid" PagerStyle-CssClass="pager"
                        HeaderStyle-CssClass="header" RowStyle-CssClass="rows"
                        AllowPaging="True" AutoGenerateDeleteButton="True" CellPadding="1" PagerSettings-PageButtonCount="5"  AutoGenerateSelectButton="True" PageSize="5" OnPageIndexChanging="datagrid_PageIndexChanging" OnRowDeleting="datagrid_RowDeleting" OnSelectedIndexChanged="datagrid_SelectedIndexChanged"  >
                    </asp:GridView>
                </div>
                </form>
            </div>
        </div>
        <hr style="width: 100%; visibility: hidden;" />
        <div class="post">
            <div class="entry">
                <div class="col-xs-5">
                    <label for="ex1">Facility Name :</label><asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="*" ControlToValidate="txtName" ForeColor="Red" ValidationGroup="reg"></asp:RequiredFieldValidator>
                    <asp:TextBox ID="txtName" runat="server" CssClass="form-control" Width="397px" ValidationGroup="reg"></asp:TextBox>
                </div>
                <div class="col-xs-5">
                    <label for="ex1">Tel No :</label><asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="*" ControlToValidate="txtTel" ForeColor="Red" ValidationGroup="reg"></asp:RequiredFieldValidator>
                    <asp:TextBox ID="txtTel" runat="server" CssClass="form-control" Width="397px" ValidationGroup="reg"></asp:TextBox>
                    <ajaxToolkit:MaskedEditExtender ID="txtTel_MaskedEditExtender" runat="server" Mask="(999)-999-9999" TargetControlID="txtTel" />
                </div>
                <hr style="width: 100%; visibility: hidden;" />
                <hr style="width: 100%; visibility: hidden;" />
                <div class="col-xs-5">
                    <label for="ex1">Physical Address :</label><asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="*" ControlToValidate="txtPhysicalAdr" ForeColor="Red" ValidationGroup="reg"></asp:RequiredFieldValidator>
                    <asp:TextBox ID="txtPhysicalAdr" runat="server" CssClass="form-control" Height="87px" Width="397px" TextMode="MultiLine" ValidationGroup="reg"></asp:TextBox>
                </div>
                <hr style="width: 100%; visibility: hidden;" />
                <div class="col-xs-5">
                    <label for="ex1">Postal Address :</label><asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ErrorMessage="*" ControlToValidate="txtPostalAdr" ForeColor="Red" ValidationGroup="reg"></asp:RequiredFieldValidator>
                    <asp:TextBox ID="txtPostalAdr" runat="server" CssClass="form-control" Height="87px" Width="397px" TextMode="MultiLine" ValidationGroup="reg"></asp:TextBox>
                </div>
                <hr style="width: 100%; visibility: hidden;" />
                <div class="meta">
                <p class="links"><asp:LinkButton ID="LBClear" runat="server" CssClass="clear" OnClick="LBClear_Click" >Clear</asp:LinkButton><b>|</b><asp:LinkButton ID="LinkButton1" runat="server" CssClass="update" OnClick="LinkButton1_Click" ValidationGroup="reg" >Update</asp:LinkButton> <b>|</b><asp:LinkButton ID="LBReg" runat="server" CssClass="reg" ValidationGroup="reg" OnClick="LBReg_Click">Register</asp:LinkButton> </p>
            </div>
            </div>
        </div>
    </div>
</asp:Content>
